# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-15 14:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180515_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 15, 14, 13, 6, 110604, tzinfo=utc)),
        ),
    ]
