# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-15 17:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180515_0913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_date']},
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 15, 17, 4, 9, 274571, tzinfo=utc)),
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
    ]
