# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-17 21:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180516_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 17, 21, 0, 52, 920953, tzinfo=utc)),
        ),
    ]
