# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-15 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_num_code', models.IntegerField()),
                ('course_name', models.CharField(max_length=200)),
                ('course_seats', models.IntegerField()),
                ('course_description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_name', models.CharField(max_length=200)),
                ('department_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('department_chair', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('course_offered', models.ManyToManyField(to='class_management.Course')),
            ],
            options={
                'db_table': 'instructors',
            },
        ),
        migrations.CreateModel(
            name='Scorecard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'scorecard',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('stud_pic', models.ImageField(blank=True, upload_to='student_pics')),
                ('courses', models.ManyToManyField(to='class_management.Course')),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='course_dept_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_management.Department'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set([('course_dept_code', 'course_num_code')]),
        ),
    ]
