# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-15 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='class_management.Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scorecard',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='class_management.Student'),
            preserve_default=False,
        ),
    ]
