# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0004_auto_20180517_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='course_offered',
            field=models.ManyToManyField(blank=True, to='class_management.Course'),
        ),
    ]
