# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0005_auto_20180521_1532'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='departments',
        ),
    ]
