# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0007_auto_20180523_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='area_code',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='number',
            field=models.DecimalField(decimal_places=0, max_digits=7),
        ),
    ]
