# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0008_auto_20180523_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='number',
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='first_three',
            field=models.DecimalField(decimal_places=0, default=555, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='last_four',
            field=models.DecimalField(decimal_places=0, default=5555, max_digits=4),
            preserve_default=False,
        ),
    ]
