# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_management', '0009_auto_20180523_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phones',
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='class_management.Student'),
        ),
    ]
